/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    DataView: typeof import('primevue/dataview')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FormField: typeof import('./src/components/utility/FormField.vue')['default']
    GameDetails: typeof import('./src/components/game/GameDetails.vue')['default']
    Image: typeof import('primevue/image')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Logo: typeof import('./src/components/navbar/Logo.vue')['default']
    Navbar: typeof import('./src/components/navbar/Navbar.vue')['default']
    NavbarIcon: typeof import('./src/components/navbar/NavbarIcon.vue')['default']
    ProfileDropdown: typeof import('./src/components/user-details/ProfileDropdown.vue')['default']
    RegisterModal: typeof import('./src/components/game/RegisterModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./src/components/utility/StatCard.vue')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
    UserDetails: typeof import('./src/components/UserDetails.vue')['default']
    UsersName: typeof import('./src/components/user-details/UsersName.vue')['default']
  }
}
