/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Image: typeof import('primevue/image')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Navbar: typeof import('./src/components/navbar/Navbar.vue')['default']
    NavbarIcon: typeof import('./src/components/navbar/NavbarIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./src/components/StatCard.vue')['default']
    UserDetails: typeof import('./src/components/UserDetails.vue')['default']
  }
}
