/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    'Global Leaderboard': RouteRecordInfo<'Global Leaderboard', '/leaderboard', Record<never, never>, Record<never, never>>,
    'Places to play': RouteRecordInfo<'Places to play', '/locations', Record<never, never>, Record<never, never>>,
    'Your Stats': RouteRecordInfo<'Your Stats', '/stats', Record<never, never>, Record<never, never>>,
    'Tournaments': RouteRecordInfo<'Tournaments', '/tournament', Record<never, never>, Record<never, never>>,
  }
}
